---
- name: Test Connection to my servers
  hosts: all
  become: yes

  tasks:

  - name: Ping my servers
    ping:

  - name: Show current hostname
    debug:
      msg: "Current host is: {{ ansible_hostname }}"
