
---
- name: My super playboochek
  hosts: all
  become: yes

  vars:
    mytext: "Privet Yarik"

  tasks:
  - name: test ping
    ping:

  - name: Creare folders
    include_tasks: create_folders.yaml

  - name: Create files
    include_tasks: create_files.yaml
