
---
- name: Loops Playbook
  hosts: all
  become: yes

  tasks:
  - name: Say hello to all
    debug: msg="Hello {{ item }}"
    loop:
      - "Vasya"
      - "Petya"
      - "Jopa"

  - name: Loop Until example
    shell: echo -n Z >> myfile.txt && cat myfile.txt
    register: output
    delay: 2
    retries: 10
    until: output.stdout.find("ZZZZ") == false

  - name: print out
    debug:
      var: output.stdout

  - name: Install many pack
    yum: name = {{ item }} state=installed
    loop:
      - python
      - tree



