#SPDX-License-Identifier: MIT-0
---
# handlers file for deploy_apache_web
- name: Restart Apache                                    
  service: name=httpd state=restarted 
  when: ansible_os_family == "RedHat" 
